# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvPcZqJg7aDos2VGYyxjD09997qZafjw
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

def company():
    path = ('/content/dataTRAIN.csv')
    train = pd.read_csv(path, sep=";")
    path = ('/content/dataTEST.csv')
    X_test = pd.read_csv(path, sep=";")

    with open(os.path.join('input', 'dataTEST.csv'), "a") as fp:
        wr = csv.writer(fp, dialect='excel')
        wr.writerow()

    # отбор данных 1
    train.drop(['Name', 'INN', 'global_id'], axis = 1, inplace = True)
    X_train = train.drop('status', axis = 1)
    y_train = train['status']
    # обучение модели 1
    model = LogisticRegression()
    model.fit(X_train, y_train)
    y_pred_df = model.predict(X_train)
    # сравнение прогнозных значений с фактическими
    conf_matrix = confusion_matrix(y_df, y_pred_df)
    conf_matrix_df = pd.DataFrame(conf_matrix)
    conf_matrix_df
    conf_matrix_labels = pd.DataFrame(conf_matrix, columns = ['Прогноз ненадежный ', 'Прогноз надежный'], index = ['Факт ненадежный', 'Факт надежный'])
    conf_matrix_labels
    # отбор данных 2
    X_test.drop(['Name', 'INN', 'global_id'], axis = 1, inplace = True)
    X_test.columns = X_test.columns.map(str)
    y_pred_test = model.predict(X_test)
    y_pred_test[:10]

    return predictions[len(predictions)-1:]['status']